### ISSUE TITLE
INCLINATION_DEG variable name

### ISSUE THREAD

**Issue by MADECICCO** [ThomasAlbin/SpaceScienceTutorial#2]
default variable name  'INCLINATION' and  'INCLINATION_DEG' causing variable name issues.

**Comment by ThomasAlbin** [comment]
Hey,

which script is causing a variable issue? I will fix everything as fast as possible!

**Comment by MADECICCO** [comment]
The first script/notebook which those variable names appeared.

Cool tutorial, I just loved them all!! Need more!!

**Comment by ThomasAlbin** [comment]
It is still presents? Otherwise I would like to close this issue.

**Comment by MADECICCO** [comment]
> It is still presents? Otherwise I would like to close this issue.

All set!!
