### ISSUE TITLE
excess of variable names  - part 7

### ISSUE THREAD

**Issue by MADECICCO** [ThomasAlbin/SpaceScienceTutorial#3]
VALUES(...) have 12 entries causing an issue .

BTW, APHELION  OR APOHELION?

# Insert the data
cur.executemany('INSERT OR REPLACE INTO ' \
                'comets_main(NAME, ' \
                            'ORBIT_TYPE, ' \
                            'PERIHELION_AU, ' \
                            'SEMI_MAJOR_AXIS_AU, ' \
                            'APHELION_AU, ' \
                            'ECCENTRICITY, ' \
                            'INCLINATION, ' \
                            'ARG_OF_PERIH_DEG, ' \
                            'LONG_OF_ASC_NODE_DEG, ' \
                            'EPOCH_UTC, ' \
                            'EPOCH_ET, ' \
                            'ABSOLUTE_MAGNITUDE, ' \
                            'SLOPE_PARAMETER'
                            ') ' \
                'VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', \
                c_df[['Designation_and_name', \
                      'Orbit_type', \
                      'Perihelion_dist', \
                      'SEMI_MAJOR_AXIS_AU', \
                      'APHELION_AU', \
                      'e', \
                      'i', \
                      'Peri', \
                      'Node', \
                      'EPOCH_UTC', \
                      'EPOCH_ET', \
                      'H', \
                      'G']].values)

**Comment by ThomasAlbin** [comment]
Hey there!

I tried to re-run part 7 (the Python script as well as the Jupyter Notebook) and there were no errors and warnings. I would kindly ask for the error message and the Library Versions you are using.

**Comment by MADECICCO** [comment]
I just copy those sricpts from your webpage I did not use scripts from git directories.  You mean kind of libraries?

**Comment by ThomasAlbin** [comment]
I think I have to update the scripts on the Medium page, since the gists are not updated automatically. In the future I will add a comment regarding updates. The most recent scripts are here on GitHub. I apologise for any inconvenience.
