### ISSUE TITLE
SPICE (NOSUCHFILE) - filename issues

### ISSUE THREAD

**Issue by MADECICCO** [ThomasAlbin/SpaceScienceTutorial#4]
SpaceScienceTutorial/part13/

When I tried to load filenames as '67P_CHURY_GERAS_2004_2016.BSP'. the function furnsh didn't accept it, despite 'file.bsp' is in the right folder. It seems some behavior related to characters filename

If I change it to , e.g., 'chgeras.BSP', it runs nicely
```


--------------------------------------------------------------------------
SpiceNOSUCHFILE                           Traceback (most recent call last)
<ipython-input-6-68654f2ffb0d> in <module>
      2 
      3 
----> 4 spiceypy.furnsh(dir+'kernel_meta.txt')

~/anaconda3/envs/space/lib/python3.8/site-packages/spiceypy/spiceypy.py in with_errcheck(*args, **kwargs)
    106         try:
    107             res = f(*args, **kwargs)
--> 108             check_for_spice_error(f)
    109             return res
    110         except BaseException:

~/anaconda3/envs/space/lib/python3.8/site-packages/spiceypy/spiceypy.py in check_for_spice_error(f)
     89         traceback = qcktrc(200)
     90         reset()
---> 91         raise stypes.dynamically_instantiate_spiceyerror(
     92             short=short, explain=explain, long=long, traceback=traceback
     93         )

SpiceNOSUCHFILE: 
================================================================================

Toolkit version: CSPICE66

SPICE(NOSUCHFILE) --

The fourth file '/home/decicco/Documents/Programas/SpaceScienceTutorial/_kernels/spk/67P_CHURY_GE' specified by KERNELS_TO_LOAD in the file /home/decicco/Documents/Programas/SpaceScienceTutorial/kernel_meta.txt could not be located.

furnsh_c --> FURNSH --> ZZLDKE

```

**Comment by ThomasAlbin** [comment]
The path in your message ...

`'/home/decicco/Documents/Programas/SpaceScienceTutorial/_kernels/spk/67P_CHURY_GE'`

... is not complete. It is missing the content after the "_GE". However, the corresponding meta kernel file contains the complete path ...

`    '../_kernels/spk/67P_CHURY_GERAS_2004_2016.BSP',`

... in line 12.

Your path appears to be 80 character long. Are you using Windows by any chance?

**Comment by MADECICCO** [comment]
I put the whole filename 67P_CHURY_GERAS_2004_2016.BSP. At the error only part of it appeared.

I am using ubuntu 18.4

**Comment by ThomasAlbin** [comment]
Just a quick question whether it works now? On Mac OS I am currently facing no issues. Again, the 80 character limitation appears to be peculiar

**Comment by MADECICCO** [comment]
> Just a quick question whether it works now? On Mac OS I am currently facing no issues. Again, the 80 character limitation appears to be peculiar

Dear Thomas,

Yes it seems a 80 character limitation,  if I use a small version of path, it runs nicely.
Some linux Ubuntu bug?

**Comment by ThomasAlbin** [comment]
I would not say it is a bug. Honestly, I do not know. Maybe there is an artificial limit set? Since it is not related to the scripts, I would close the issue
