### ISSUE TITLE
year description on the header line does not correspond to variable 'year'

### ISSUE THREAD

**Issue by MADECICCO** [ThomasAlbin/SpaceScienceTutorial#5]
In the part 14 :

`# Now we want to determine when 67P enters the SOI of Jupiter. As a starting
# date we set the 1st January 1961 and compute everything back in time
datetime_stamp = datetime.datetime(year=2017, month=1, day=1)`

Instead , 1st January 2017

**Comment by ThomasAlbin** [comment]
Fixed. Thanks a lot!
