### ISSUE TITLE
Meta kernel tutorial format not working, furnshing meta kernels broken on mac, all kernels for part 6 not working.

### ISSUE THREAD

**Issue by Quessian-Phaedrus-Sternabite** [ThomasAlbin/SpaceScienceTutorial#8]
The Meta Kernels used in this tutorial do not work for any projects I attempted. For a colleague, furnshing meta-kernels even in a format working on windows did not work. Finally, on part 6 of the tutorial, no format works, not even furnshing kernels line by line. Attempting to run the code results in this error: 
![error](https://user-images.githubusercontent.com/56981027/106929720-5468f380-66da-11eb-882e-52962f43a502.png)

**Comment by ThomasAlbin** [comment]
Hey there! That is strange. Can you write a Python script with a furnsh command that loads a single file (e.g., the naif0012 leapseconds kernel)? For convenience put the kernel in the same directory as the Python script and try to execute it. Unfortunately I cannot test the setup on Windows to determine whether this is an OS issues or not.

**Comment by Quessian-Phaedrus-Sternabite** [comment]
*Written in real-time. Line breaks to show passage of time.

Loading just naif0012 works. I used this:
```
import spiceypy
spiceypy.furnsh('naif0012.tls')
x = spiceypy.ktotal("ALL")
print(x)
```
to test it, and it returns one. Let me try adding a second one.

Adding in:
`spiceypy.furnsh('gm_de431.tpc')`
Results in an output of two. I'm going to try to load all the ones seen in the tutorial to determine if it's a problem with the specific kernels. 

Adding in 'codes_300ast_20100725.bsp' worked. 

Doing the .tf file worked. 

Hmm. All five in the meta kernel work and show up as being furnshed in the test. Copying the test code over to the project file resulted in the same error as seen above...

Something interesting happened. When I furnshed the meta kernel, it returns 6, but when I manually furnsh, it returns 5.

By testing the meta kernel, it seems that it loads correctly, still loading 6 when only five kernels were specified, on the project. From what I've seen, this seems to not be a furnshing error, but rather one with something in the code. I tried copying your code directly, and I am going to add you to my repository access in case you need to view the test files.

**Comment by ThomasAlbin** [comment]
Thank you very much for your detailed description. Now this is really weird since I did not encounter this issue. I will dive deep into this and try to reproduce it in a way.

But speaking of inconsistency, your issue gave me an idea: Maybe I should provide a docker container where everyone will have the same environment. Since I am currently working on a library that shall be later used to continue the tutorial series; a docker file could be a nice add-on.

**Comment by Quessian-Phaedrus-Sternabite** [comment]
Thank you for responding! Hopefully doing a container could work, although I don't know how easy it'd be for the tutorial followers to get set up. I'll keep looking into the issue. Is DAFNOSUCHHANDLE a known issue?

**Comment by ThomasAlbin** [comment]
I am thinking to setup something called "remote containers" for VS Code. Providing setup and pre-defined config files will install everything for the user and it is way simpler than setting up a Python virtual env.

The error is a custom error defined by SPICE itself.

**Comment by ThomasAlbin** [comment]
So somehow I am not able to reproduce the error. May I ask for your Operating System? I tested it on Mac and Linux. I would add a hint on the general description that the tutorial may not work as intended on all systems.

**Comment by Quessian-Phaedrus-Sternabite** [comment]
I am currently on windows 10 using python 64 on PyCharm. I have been using a venv, and installed all packages correctly.

**Comment by Quessian-Phaedrus-Sternabite** [comment]
After extensive testing, I believe the error was a corrupt file download of kernels in the _misc folder caused by unknown factors. Attempting to purge the _kernels folder and restoring from the tutorial GitHub, then running the download script resolved this problem. I will create a new error continuing the subject of meta kernel errors, but for now, the part 6 error is resolved. I apologise for not finding this earlier, and would like to thank you for being so helpful, as well as taking the time to respond.
